--Login as Admin user from SQL Developer and run below commands

DROP USER DormRating CASCADE;

CREATE USER DormRating IDENTIFIED BY DAMG6210Project#;

ALTER USER DormRating DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;

ALTER USER DormRating TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO DormRating;

GRANT CREATE SESSION, CREATE VIEW, CREATE TABLE, ALTER SESSION, CREATE SEQUENCE TO DormRating;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE, UNLIMITED TABLESPACE TO DormRating;